### ISSUE TITLE
Self-drive in the Test scene not long enough

### ISSUE THREAD

**Issue by MaxWaechter** [farbod69/Westdrive-LoopAR#459]
The self-drive time in the training scene is not long enough. I just tried to do that and I had only 3 seconds or so to drive by myself before the automated drive switched. Maybe you could try to have the automated drive first? I don't know yet, but for now this sees to be a bug.

**Comment by FredHaus93** [comment]
I just had the timer set to 5 seconds so I could test the AI drive part better without having to do 30 seconds of self-drive all the time. You can just set the amount of seconds you want to have under TestEventManager under the first point "Time for Control".
Changed and pushed that.

**Comment by nora-maleki** [comment]
It is adjusted.
