### ISSUE TITLE
Data Saving in Training Scene

### ISSUE THREAD

**Issue by MaxWaechter** [farbod69/Westdrive-LoopAR#460]
Data saving in the training scene is missing. No Data is saved from the training scene. That should be fixed.

**Comment by FredHaus93** [comment]
Checked again and found the reason why it did not save properly. Should be fixed now.

**Comment by nora-maleki** [comment]
@FredHaus93 
The data saving issue is fixed. There are still other issues in training scene which I open in github but you can close this one.
