### ISSUE TITLE
Finalizing Autobahn Roads

### ISSUE THREAD

**Issue by MaxWaechter** [farbod69/Westdrive-LoopAR#463]
Hey hey,

We found in the built version, that the terrain is showing immensly through the road. Actually, there weren't any pieces of roads visable. This needs to be fixed. Nora said, that it would be helpful, if you could finalize the roads on that. 

@farbod69 we are not sure if we should keep a editable brnach as copy. But we need to finalize 2 Weeks before the event end. 
Therefore we are proposing a hard finalization of the road network right now

**Comment by maxpingel** [comment]
Last time i build the roads, i selected don't update terrain and it worked

**Comment by MaxWaechter** [comment]
Well that is weird. Nora was building the scene and then it was not drivable all over sudden. If we have the same issue tomorrow, I'll add a picture of this here.

**Comment by MaxWaechter** [comment]
Anyway - the editable road networks seem to take up a lot of resources and the finalized road seem to be faster in loading. We'll have a look at this tomorrow, but finalizing seems to be a good idea anyway.

**Comment by MaxWaechter** [comment]
We just checked and the problem is still there. Farbod will tell in the group that it would be cool to finalize the road network.
