### ISSUE TITLE
EyeValidation Position of Cross and fixation Dot are not independant of SteamVR Position

### ISSUE THREAD

**Issue by Z3rca** [farbod69/Westdrive-LoopAR#469]
See title. When running the eyeValidation, the cross and the fixation dot is sometimes off. This is because of the origin Position set in SteamVR(When you basically calibrate VR). If you are not in the exact Position of Steam VR, the fixation dot and the cross are off, which looks very weird and feels confusing. 

Workaround: if you encounter that problem, just do recalibration of SteamVR.

Potential Solution: The Cross might take the direction and position of the Participant into account.

**Comment by nora-maleki** [comment]
[IMPORTANT] Steam VR calibration must be done after the technical setup is done and before testing the participants.
