### ISSUE TITLE
Inconsistent HUD Markings

### ISSUE THREAD

**Issue by MaxWaechter** [farbod69/Westdrive-LoopAR#482]
Inconsistend marking of the car. We just saw that sometimes we have Box colliders, sometimes we have Mesh coliders. 
We weren't really sure what to use, but for the sake of computational power, we would say the box colider is it.

**Comment by maxpingel** [comment]
so everything to Box?

**Comment by nora-maleki** [comment]
> so everything to Box?

True :)

**Comment by maxpingel** [comment]
Autobahn is done
