### ISSUE TITLE
Activation Triggers in Events

### ISSUE THREAD

**Issue by MaxWaechter** [farbod69/Westdrive-LoopAR#483]
In Autobahn, there are activation triggers in the events. Relocate them, because they won't work if test subjects fails before going through these triggers. So move them forwards. 

This still needs testing later on.

**Comment by nora-maleki** [comment]
![ActivationTriggersDisplacedAutobahn3](https://user-images.githubusercontent.com/50799852/92321882-e8e90000-f02d-11ea-8400-2ac02688b6ea.PNG)

![ActivationTriggersDisplacedAutobahn2](https://user-images.githubusercontent.com/50799852/92321885-ed151d80-f02d-11ea-947e-b86ca936ca14.PNG)

![ActivationTriggersDisplacedAutobahn1](https://user-images.githubusercontent.com/50799852/92321888-f0100e00-f02d-11ea-8a62-90134e351c76.PNG)

Activation triggers should be placed in a way that are hit in any case. When participant fails, they start from the re-spawn point (the pink one) and therefore the triggers behind that point don't get hit.

**Comment by nora-maleki** [comment]
![ActivationTriggersNoHitAutobahn1](https://user-images.githubusercontent.com/50799852/92321948-86443400-f02e-11ea-8cdb-4595b05a1090.PNG)

This one is also not on the path of the participant's car and doesn't get hit most probably. It would be also really nice if you could check if all are on the path :)

**Comment by MaxWaechter** [comment]
@Noraaaaaaa thanks a lot for the hints and explainations.
