### ISSUE TITLE
Fail situation in training scene doesn't allow participant to continue

### ISSUE THREAD

**Issue by nora-maleki** [farbod69/Westdrive-LoopAR#489]
![TrainingSceneFailScenario](https://user-images.githubusercontent.com/50799852/92306657-1a5fbe00-ef91-11ea-817c-967e7004bbff.PNG)

This happens when one fails in the training.

**Comment by FredHaus93** [comment]
Found the problem and fixed it. Should now properly continue. Change is already pushed.

**Comment by nora-maleki** [comment]
> Found the problem and fixed it. Should now properly continue. Change is already pushed.

It does :)
