### ISSUE TITLE
The cyclist position at end of the path

### ISSUE THREAD

**Issue by nora-maleki** [farbod69/Westdrive-LoopAR#490]
![WeirdCyclistPositionCountryRoad](https://user-images.githubusercontent.com/50799852/92308898-687cbd80-efa1-11ea-979b-f530ecc3801d.PNG)

The cyclist stays like this at end of its path. He could be adjusted so, that it doesn't go to the ground.

**Comment by nora-maleki** [comment]
@MaxWaechter please check whether this issue is low priority for the pilot study.

**Comment by lmlightbulb** [comment]
Made the cyclist drive up the forest path
