### ISSUE TITLE
Gohst Driver event

### ISSUE THREAD

**Issue by nora-maleki** [farbod69/Westdrive-LoopAR#495]
![GohstDriverAutobahn](https://user-images.githubusercontent.com/50799852/92323421-e213ba80-f038-11ea-8bcf-e06c315df436.PNG)

The light doesn't make sense here :D

**Comment by nora-maleki** [comment]
@MaxWaechter Please check if this is urgent or can wait until after pilot study :)

**Comment by MaxWaechter** [comment]
Hahah. Thx for putting me in this loop, and yess - this does not influence the experiment in any way. I'd even say we close this issue.

**Comment by nora-maleki** [comment]
> Hahah. Thx for putting me in this loop, and yess - this does not influence the experiment in any way. I'd even say we close this issue.

:D But it's almost a 4 to 5 click fix. Let's mark it as low priority and after pilot study we can refine :)
