### ISSUE TITLE
Unmarked event object in Westbrueck

### ISSUE THREAD

**Issue by nora-maleki** [farbod69/Westdrive-LoopAR#496]
![Event2City](https://user-images.githubusercontent.com/50799852/92323491-8ac21a00-f039-11ea-9f9a-1cc2f367e236.gif)

### The van is not marked and there is a collider on the side of the road which stopped the car.

![Event2CityTrim](https://user-images.githubusercontent.com/50799852/92323542-ec828400-f039-11ea-876f-62db278e4e16.gif)

**Comment by Jogurth** [comment]
It's just normal traffic, I don't think the HUD should react. if you just wait for the ambulance to cross the street (as most normal drivers do) the van is no problem
