### ISSUE TITLE
The car interfering and blocking the participant

### ISSUE THREAD

**Issue by nora-maleki** [farbod69/Westdrive-LoopAR#518]
![CountryRoad](https://user-images.githubusercontent.com/50799852/92641315-d6e1b880-f2de-11ea-8888-187fdc5cab32.PNG)

This the new car which is interfering. 

Solution: either moving it further or removing it or parking it somewhere.

**Comment by lmlightbulb** [comment]
I cant replicate the bug, and there should'nt be a red car at all :D Is it still relevant @Noraaaaaaa ?

**Comment by nora-maleki** [comment]
> I cant replicate the bug, and there shouldn't be a red car at all :D Is it still relevant @Noraaaaaaa ?

I test today and if it was there, I contact you
